name: Validacion Arquitectonica

on:
  push:
    branches: [ main, master, develop ]

  pull_request:
    branches: [ main, master ]

jobs:

  arquitectura:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Dar permisos a mvnw
        run: chmod +x mvnw

      - name: Ejecutar reglas ArchUnit
        run: ./mvnw test -Dtest=ReglasArquitectura --no-transfer-progress

      - name: Ejecutar pruebas completas
        run: ./mvnw verify --no-transfer-progress